### ISSUE TITLE
Request:  Add support for "Empty Dust" for models with self empty station

### ISSUE THREAD

**Issue by psperry** [DeebotUniverse/docs#103]
Emptying is loud. It would be nice to be able to schedule it for when we are awake.

**Comment by edenhaus** [comment]
Please don't open the same issue in multiple repos....
For everyone please refer to https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/discussions/132

**Comment by vandalon** [comment]
Hi, I'm sorry to mention this again, but the URL above does not seem to work any more. Is there any chance this will get implemented if at all possible? Or maybe it already is but I did not found how to? :P
