### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by lloydwood** [DeebotUniverse/docs#118]
I get:

 Can't connect to the ecovacs API

when I try to add the integration. I'm using GB, EU as country codes.

There are no logs because I haven't managed to get the integration added!

**Comment by rosstroha** [comment]
I think Ecovacs was having issues yesterday. There was a really long delay when I tried doing anything in the Ecovacs app.

**Comment by edenhaus** [comment]
Closing due inactivity
