### ISSUE TITLE
Request: Add Ecovacs room naming to the documentation

### ISSUE THREAD

**Issue by danielcopper** [DeebotUniverse/docs#145]
Maybe it would be helpful to add the room names that ecovacs uses internally to the documentation.
Would help a lot for writing the configuration part when you have a lot of rooms.

And maybe an example on what to do if you have two bathrooms.

I don't want to delegate work, so if it's okay I would open up a PR myself.

**Comment by edenhaus** [comment]
Pr are always welcome 😊 
Newer models support custom naming and not all models support all types. As I don‘t have information, which models support which room types, I‘m not sure if it is useful to put the names of the rooms in the docs.

**Comment by danielcopper** [comment]
Ok good to know.

Is there a way to read out the internal names? Trying to send the deebot to the storage room and the office but no luck so far.
I have the 950 btw.

**Comment by mrbungle64** [comment]
> Ok good to know.
> 
> Is there a way to read out the internal names? Trying to send the deebot to the storage room and the office but no luck so far. I have the 950 btw.

@danielcopper 
This should be the (full) list of room names for OZMO 920/950 devices:
https://github.com/mrbungle64/ecovacs-deebot.js/blob/d0b950941696d0fc8d023d8595b95188aec60151/library/mapTemplate.js#L11

**Comment by danielcopper** [comment]
Awesome thanks a lot

**Comment by bachoo786** [comment]
Hi there

In the example you have given, how do I know what is my room number?

```
service: vacuum.send_command
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
data:
  command: spot_area
  params:
    rooms: 10,14
    cleanings: 1
```

I have tried giving random numbers to the rooms but it doesnt work and my deebot_n8 just moves from the charging station and doesnt clean any room.

**Comment by edenhaus** [comment]
Your vacuum has a attribute `rooms`, where you are able to find them out. Easiest way to access them are over the developer tools

![Screenshot_20220929-163829](https://user-images.githubusercontent.com/26537646/193061864-e053c3fb-bcda-4238-b9b9-9883c440fdde.jpg)

**Comment by bachoo786** [comment]
I am under the developer tools but what entity am I looking at?

I got the following under the vacuum.deebot_n8 :

![image](https://user-images.githubusercontent.com/6251030/193065564-97a854c3-74f2-4075-ad58-dc5d124e6fc3.png)

But still can't see the rooms. What shall I do? Do I have to set it up in the deebot app on my phone?

**Comment by edenhaus** [comment]
As you don‘t have setup a room type via the app you have all room numbers under default

**Comment by bachoo786** [comment]
> As you don‘t have setup a room type via the app you have all room numbers under default

Oh right and how do I do that on the app? To be honest the app is not as good as the one of the xiaomi vacuums. 

I cannot use area cleaning on the app either the vacuum would move a metre from the charging station and it would just stop there spinning the brushes for hours. 

Do you know what could be wrong?

**Comment by bachoo786** [comment]
> As you don‘t have setup a room type via the app you have all room numbers under default

So how do I set up a room type in the app?

**Comment by edenhaus** [comment]
Please refer to the ecovacs help in the app or on the website

**Comment by bachoo786** [comment]
> Please refer to the ecovacs help in the app or on the website

Ok I managed to change room type on the app. However on HA I still don't see the room label etc. Please see below the latest screenshot.

![Screenshot_20220929-215313_Home Assistant](https://user-images.githubusercontent.com/6251030/193139873-4f208ccf-6a91-4363-b287-6696573ec5fb.png)

**Comment by edenhaus** [comment]
Request a manual refetch via the deebot service or on the next cleaning it will be updated.

**Comment by edenhaus** [comment]
You need first to setup correctly your map via the app and the map must be saved. Afterwards you can you all the features For help about the app please refer directly to the ecovacs help in the app or on the website. Am 29.09.2022 18:59 schrieb bachoo786 ***@***.***>:



As you don‘t have setup a room type via the app you have all room numbers under default



Oh right and how do I do that on the app? To be honest the app is not as good as the one of the xiaomi vacuums.

I cannot use area cleaning on the app either the vacuum would move a metre from the charging station and it would just stop there spinning the brushes for hours.

Do you know what could be wrong?
