### ISSUE TITLE
Login succesfull - but no deebot -.-

### ISSUE THREAD

**Issue by crosserSniper** [DeebotUniverse/docs#168]
Dear everyone,

when I try to implement my Deebot OZMO 930, I could log in (with wrong Log-In there is also a error msg), but my deebot is not shown in the last pic.
What I#m doing wrong? Is the Deebot OZMO 90 compatible?

![grafik](https://user-images.githubusercontent.com/110885066/184473654-ca8f0861-7d12-4e91-8f92-d9be96af9afb.png)
![grafik](https://user-images.githubusercontent.com/110885066/184473673-65590a5a-9e0d-446e-a4d3-73acccebea92.png)
![grafik](https://user-images.githubusercontent.com/110885066/184473689-97434bd7-37cd-419e-858e-22b61b5809f4.png)

**Comment by vekexasia** [comment]
@crosserSniper did you fix this?

**Comment by crosserSniper** [comment]
yes - I have no supported deebot -.- 
I did it with an nodeRed flow
