### ISSUE TITLE
Deebot 900 not working

### ISSUE THREAD

**Issue by kravalli** [DeebotUniverse/docs#171]
Hi,

I have a deebot 900. The integration setup was flawless and sees to work, however the status of the vacuum is always unkown and I can't do anything (start, stop, return to chargingdock). I have no error, what is the problem?

Thanks in advance.

**Comment by edenhaus** [comment]
This is thr documentation repo, which is used for multiple integration. On https://deebot.readthedocs.io/home/models/ you can find, which integration supports which model
