### ISSUE TITLE
Question about iot/atr channel to receive information when the robot data changes

### ISSUE THREAD

**Issue by cpadil** [DeebotUniverse/docs#176]
Hello,

Thank you for this integration!

I was going through the docs and as per the Advance section, there is a way to suscribe to a channel to get updated automatically without the need of manual refresh, am i correct?
https://deebot.readthedocs.io/advanced/protocols/mqtt/

if my understanding is correct, could you please point me to the right direction to do this in Home assistant?

Thanks

**Comment by edenhaus** [comment]
The Deebot 4 HA integration is already using mqtt. Only at startup or if you request a manually update, we poll the data
