### ISSUE TITLE
Cannot login from Integration setup

### ISSUE THREAD

**Issue by nickelnine** [DeebotUniverse/docs#184]
I'm trying my newly created account on the Integration setup window and whenever I click 'Submit', I get this back:

![image](https://user-images.githubusercontent.com/28116390/192650049-4b4de0f1-3be8-4ece-8167-301c1d82c480.png)

I verified my user/password and using US/NA as country/continent but no luck getting setup.

**Comment by edenhaus** [comment]
The integration is not supporting your model.
Ecovacs uses three different protocols and the integration supports only the newest one.

In the next version a better error message will be displayed
