### ISSUE TITLE
userinfo

### ISSUE THREAD

**Issue by tpbillund** [DeebotUniverse/docs#201]
Hi
I am trying to add this to my HA [DeeBot 4 HA](https://deebot.readthedocs.io/integrations/home-assistant/) and it asking me for a email and password??
I have never added a password to my tablet, I have just installed the ECOVACS home app scanned the QR and the DeeBot T10 Plus is running.
Where do I get this email/password info, or can I some-how skip that?

**Comment by mrbungle64** [comment]
@tpbillund 

You can check if you already registered at Ecovacs:
"Mine" -> "Settings" -> "Account and security"

**Comment by mrbungle64** [comment]
@tpbillund 

> You can check if you already created an Ecovacs account:
> "Mine" -> "Settings" -> "Account and security"

Have you already checked your account settings?

> or can I some-how skip that?

No, you cannot skip that

**Comment by mrbungle64** [comment]
@tpbillund 

> I have just installed the ECOVACS home app scanned the QR and the DeeBot T10 Plus is running.

Of course you can run your bot without using the Ecovacs Home App as illustrated in the instructions, but for most of the functionality you have to register with email (or Ecovacs ID) / password and use the Ecovacs Home App.

![Operating Deebot 2023-01-10 08 17 58](https://user-images.githubusercontent.com/37313763/211486411-809d5552-82b8-468a-8ba4-4facbc4b802b.png)

**Comment by mrbungle64** [comment]
No response from the user and he should now have received sufficient information.
The supposed issue seems to be solved.
