### ISSUE TITLE
Have to keep reloading integration?

### ISSUE THREAD

**Issue by thepuncake** [DeebotUniverse/docs#230]
Hi there and thanks for this, I have a strange problem however. After some time the vacuum shows as unavailable even if it is actively cleaning. Reloading the integration fixes it for a while before it goes unavailable again. Anyone experiencing the same or somebody with a fix? Appreciated!

**Comment by edenhaus** [comment]
Your issue sounds like https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/293. I'm working on it, please give me some time.

P.S. Please open the next time the issue directly on the integration repo
