### ISSUE TITLE
Casting video

### ISSUE THREAD

**Issue by sushant-here** [DeebotUniverse/docs#235]
Hi,
I would like to set up HomeAssistant automation where the vacuum map(camera) feed would be cast to the TV and/or smart display if it's not being used while the vacuum is started. 

Seems it's not possible to use the "camera: play steam" service on the live map. It gives this error:
```
Failed to call service camera.play_stream. camera.deebot_live_map does not support play stream service
```

Not sure if this is a known limitation - but would it be possible to address this?

**Comment by edenhaus** [comment]
Closing it as the camera entity was replaced by an image one. As in fact the map is only a image.
