### ISSUE TITLE
number clean_count entity

### ISSUE THREAD

**Issue by harphere** [DeebotUniverse/docs#254]
I have a Deebot Ozmo T8 which exposes a `number.{vacuum}_clean_count` entity but this number does not increment, it stays constant at '1'. I think it should increment after each completed cleaning cycle. Is this something you can kindly look into?

![image](https://github.com/DeebotUniverse/docs/assets/28116390/faadc8db-3f06-4ea7-a94f-17b18cb00d3d)

**Comment by edenhaus** [comment]
The sensor `stats_total_cleanings` counts the total cleanings.
The number entity specifies how often a room should be cleaned in one cycle. Maybe I should rename it

**Comment by harphere** [comment]
Ah, got it. Is there a way to reset `stats_total_cleanings`? I'd like to have a notification to empty the vacuum after x cleanings.

**Comment by edenhaus** [comment]
I don't think so as the app does not have this functionality. 
But I think it could be easily solved in HA. Create an input helper number, where you store the total number when you have emptied the vacuum. Create an automation, that notifies you, when the total number of the sensor is larger by 20 as the input helper number.
You could use also a custom button to store the total cleanings in the input helper when you press the button.
