### ISSUE TITLE
Llooking forward to supporting DEEBOT DD37! Hope to support the control of DEEBOT DD37 Thank you!

### ISSUE THREAD

**Issue by yun888yan** [DeebotUniverse/docs#257]
We are looking forward to supporting DEEBOT DD37! Hope to support the control of DEEBOT DD37 Thank you!

**Comment by edenhaus** [comment]
As ecovacs has not published any api documentation, only you can add support for it. Please check https://github.com/DeebotUniverse/client.py for adding supoort
