### ISSUE TITLE
Add button configuration for the "Advanced Example"

### ISSUE THREAD

**Issue by bimbam333** [DeebotUniverse/docs#67]
Hi,

in the "Advanced Example" on the website [https://deebot.readthedocs.io/integrations/home-assistant/examples/ui/advanced/](https://deebot.readthedocs.io/integrations/home-assistant/examples/ui/advanced/) the code for the start and locate button after the room selection is missing. Please complete this.

Thank you

**Comment by edenhaus** [comment]
For the next time please write something like "Can you please add/share also the configuration of the buttons..." instead of code is missing. It sounds better :smile:

Never the less I have added also the configuration for the buttons
