### ISSUE TITLE
Deebot 901

### ISSUE THREAD

**Issue by LoganJFisher** [DeebotUniverse/docs#87]
I'm trying to make sense of how to properly integrate my Deebot 901 into Home Assistant.

From [this page](https://deebot.readthedocs.io/home/models/) and [this page](https://deebot.readthedocs.io/home/projects/), I see that there are five integrations available that should work for me. I'd like whichever one is the most feature rich, like Deebot 4 Home Assistant, which unfortunately doesn't support the Deebot 901 itself. I'm very much confused on how to add any of these options (except for Deebot 4 Home Assistant, which I understand completely) can be integrated into Home Assistant.

Suffice to say, any help you can offer would be appreciated. Thanks.

**Comment by mrbungle64** [comment]
@LoganJFisher 

If you want to use the Deebot 901 in Home Assistant you can use the [Node-RED node](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot) with the [Node-RED add-on](https://github.com/hassio-addons/addon-node-red).

With the Node-RED node, practically all features of the Deebot 901 are available.

**Comment by LoganJFisher** [comment]
Thank you.
